config/routes.rb
Crave::Application.routes.draw do

  mount Spree::Core::Engine, :at => '/'

  Spree::Core::Engine.add_routes do
  
    get '/terms', :to => 'home#terms'
    get '/privacy', :to => 'home#privacy'
    
  end
  

  

end

app/models/spree/variant.rb
module Spree
  class Variant < ActiveRecord::Base
    acts_as_paranoid

    belongs_to :product, touch: true, class_name: 'Spree::Product'

    delegate_belongs_to :product, :name, :description, :permalink, :available_on,
                        :tax_category_id, :shipping_category_id, :meta_description,
                        :meta_keywords, :tax_category, :shipping_category

    has_many :inventory_units
    has_many :line_items

    has_many :stock_items, dependent: :destroy
    has_many :stock_locations, through: :stock_items
    has_many :stock_movements

    has_and_belongs_to_many :option_values, join_table: :spree_option_values_variants, class_name: "Spree::OptionValue"
    has_many :images, -> { order(:position) }, as: :viewable, dependent: :destroy, class_name: "Spree::Image"

    has_one :default_price,
      -> { where currency: Spree::Config[:currency] },
      class_name: 'Spree::Price',
      dependent: :destroy

    delegate_belongs_to :default_price, :display_price, :display_amount, :price, :price=, :currency 

    has_many :prices,
      class_name: 'Spree::Price',
      dependent: :destroy

    validate :check_price
    validates :price, numericality: { greater_than_or_equal_to: 0 }, presence: true, if: proc { Spree::Config[:require_master_price] }

    validates :cost_price, numericality: { greater_than_or_equal_to: 0, allow_nil: true }

    before_validation :set_cost_currency
    after_save :save_default_price
    after_create :create_stock_items
    after_create :set_position

    # default variant scope only lists non-deleted variants
    scope :deleted, lambda { where('deleted_at IS NOT NULL') }

    def self.active(currency = nil)
      joins(:prices).where(deleted_at: nil).where('spree_prices.currency' => currency || Spree::Config[:currency]).where('spree_prices.amount IS NOT NULL')
    end

    def cost_price=(price)
      self[:cost_price] = parse_price(price) if price.present?
    end

    # returns number of units currently on backorder for this variant.
    def on_backorder
      inventory_units.with_state('backordered').size
    end

    def options_text
      values = self.option_values.joins(:option_type).order("#{Spree::OptionType.table_name}.position asc")

      values.map! do |ov|
        "#{ov.option_type.presentation}: #{ov.presentation}"
      end

      values.to_sentence({ words_connector: ", ", two_words_connector: ", " })
    end

    def gross_profit
      cost_price.nil? ? 0 : (price - cost_price)
    end

    # use deleted? rather than checking the attribute directly. this
    # allows extensions to override deleted? if they want to provide
    # their own definition.
    def deleted?
      deleted_at
    end

    def set_option_value(opt_name, opt_value)
      # no option values on master
      return if self.is_master

      option_type = Spree::OptionType.where(name: opt_name).first_or_initialize do |o|
        o.presentation = opt_name
        o.save!
      end

      current_value = self.option_values.detect { |o| o.option_type.name == opt_name }

      unless current_value.nil?
        return if current_value.name == opt_value
        self.option_values.delete(current_value)
      else
        # then we have to check to make sure that the product has the option type
        unless self.product.option_types.include? option_type
          self.product.option_types << option_type
          self.product.save
        end
      end

      option_value = Spree::OptionValue.where(option_type_id: option_type.id, name: opt_value).first_or_initialize do |o|
        o.presentation = opt_value
        o.save!
      end

      self.option_values << option_value
      self.save
    end

    def option_value(opt_name)
      self.option_values.detect { |o| o.option_type.name == opt_name }.try(:presentation)
    end

    def has_default_price?
      !self.default_price.nil?
    end

    def price_in(currency)
      prices.select{ |price| price.currency == currency }.first || Spree::Price.new(variant_id: self.id, currency: currency)
    end

    def amount_in(currency)
      price_in(currency).try(:amount)
    end

    def name_and_sku
      "#{name} - #{sku}"
    end

    # Product may be created with deleted_at already set,
    # which would make AR's default finder return nil.
    # This is a stopgap for that little problem.
    def product
      Spree::Product.unscoped { super }
    end
    
    def in_stock?(quantity=1)
      Spree::Stock::Quantifier.new(self).can_supply?(quantity)
    end

    def total_on_hand
      Spree::Stock::Quantifier.new(self).total_on_hand
    end

    private
      # strips all non-price-like characters from the price, taking into account locale settings
      def parse_price(price)
        return price unless price.is_a?(String)

        separator, delimiter = I18n.t([:'number.currency.format.separator', :'number.currency.format.delimiter'])
        non_price_characters = /[^0-9\-#{separator}]/
        price.gsub!(non_price_characters, '') # strip everything else first
        price.gsub!(separator, '.') unless separator == '.' # then replace the locale-specific decimal separator with the standard separator if necessary

        price.to_d
      end

      # Ensures a new variant takes the product master price when price is not supplied
      def check_price
        if price.nil? && Spree::Config[:require_master_price]
          raise 'No master variant found to infer price' unless (product && product.master)
          raise 'Must supply price for variant or master.price for product.' if self == product.master
          self.price = product.master.price
        end
        if currency.nil?
          self.currency = Spree::Config[:currency]
        end
      end

      def save_default_price
        default_price.save if default_price && (default_price.changed? || default_price.new_record?)
      end

      def set_cost_currency
        self.cost_currency = Spree::Config[:currency] if cost_currency.nil? || cost_currency.empty?
      end

      def create_stock_items
        StockLocation.all.each do |stock_location|
          stock_location.propagate_variant(self) if stock_location.propagate_all_variants?
        end
      end

      def set_position
        self.update_column(:position, product.variants.maximum(:position).to_i + 1)
      end
  end
end

require_dependency 'spree/variant/scopes'

app/models/spree/variant/scopes.rb
module Spree
  class Variant < ActiveRecord::Base
    #FIXME WARNING tested only under sqlite and postgresql
    scope :descend_by_popularity, -> { order("COALESCE((SELECT COUNT(*) FROM  #{LineItem.quoted_table_name} GROUP BY #{LineItem.quoted_table_name}.variant_id HAVING #{LineItem.quoted_table_name}.variant_id = #{Variant.quoted_table_name}.id), 0) DESC") }

    class << self
      # Returns variants that match a given option value
      #
      # Example:
      #
      # product.variants_including_master.has_option(OptionType.find_by(name: 'shoe-size'), OptionValue.find_by(name: '8'))
      def has_option(option_type, *option_values)
        option_types = OptionType.table_name

        option_type_conditions = case option_type
        when OptionType then { "#{option_types}.name" => option_type.name }
        when String     then { "#{option_types}.name" => option_type }
        else                 { "#{option_types}.id"   => option_type }
        end

        relation = joins(:option_values => :option_type).where(option_type_conditions)

        option_values_conditions = option_values.each do |option_value|
          option_value_conditions = case option_value
          when OptionValue then { "#{OptionValue.table_name}.name" => option_value.name }
          when String      then { "#{OptionValue.table_name}.name" => option_value }
          else                  { "#{OptionValue.table_name}.id"   => option_value }
          end
          relation = relation.where(option_value_conditions)
        end

        relation
      end

      alias_method :has_options, :has_option
    end
  end
end

app/controllers/spree/admin/variants_controller.rb
module Spree
  module Admin
    class VariantsController < ResourceController
      belongs_to 'spree/product', :find_by => :permalink
      new_action.before :new_before

      # override the destory method to set deleted_at value
      # instead of actually deleting the product.
      def destroy
        @variant = Variant.find(params[:id])
        if @variant.destroy
          flash[:success] = Spree.t('notice_messages.variant_deleted')
        else
          flash[:success] = Spree.t('notice_messages.variant_not_deleted')
        end

        respond_with(@variant) do |format|
          format.html { redirect_to admin_product_variants_url(params[:product_id]) }
          format.js  { render_js_for_destroy }
        end
      end

      protected
        def new_before
          @object.attributes = @object.product.master.attributes.except('id', 'created_at', 'deleted_at',
                                                                        'sku', 'is_master')
          # Shallow Clone of the default price to populate the price field.
          @object.default_price = @object.product.master.default_price.clone
        end

        def collection
          @deleted = (params.key?(:deleted) && params[:deleted] == "on") ? "checked" : ""

          if @deleted.blank?
            @collection ||= super
          else
            @collection ||= Variant.where(:product_id => parent.id).deleted
          end
          @collection
        end
    end
  end
end

app/views/spree/admin/variants/_autocomplete.js.erb
<script type='text/template' id='variant_autocomplete_template'>
  <div class='variant-autocomplete-item'>
    <figure class='variant-image'>
      {{#if variant.image }}
        <img src='{{variant.image}}' />
      {{ else }}
        <img src='<%= image_path("noimage/mini.png") %>' />
      {{/if}}
    </figure>

    <div class='variant-details'>

      <h6 class="variant-name">{{variant.name}}</h6>

      {{#if variant.option_values}}
        {{#each variant.option_values}}
          <strong>{{this.option_type_presentation}}:</strong> {{this.presentation}}<br>
        {{/each}}
      {{/if}}
      
      <strong><%= Spree.t(:sku) %>:</strong> {{variant.sku}}

    </div>
  </div>
</script>

app/views/spree/admin/variants/_autocomplete_stock.js.erb
<script type='text/template' id='variant_autocomplete_stock_template'>
  <fieldset>
    <legend align="center"><%= Spree.t(:select_stock) %></legend>
      <table class="stock-levels" data-hook="stock-levels">
        <colgroup>
          <col style="width: 30%;" />
          <col style="width: 40%;" />
          <col style="width: 20%;" />
          <col style="width: 10%;" />
        </colgroup>
        <thead>
          <th><%= Spree.t(:location) %></th>
          <th><%= Spree.t(:count_on_hand) %></th>
          <th><%= Spree.t(:quantity) %></th>
          <th class="actions"></th>
        </thead>
        <tbody>
          {{#each variant.stock_items}}
            <tr>
              <td>{{this.stock_location_name}}</td>
              {{#if this.available}}
                <td>
                  {{this.count_on_hand}}
                  {{#if this.backorderable}} (<%= Spree.t(:backorders_allowed) %>) {{/if}}
                </td>
                <td>
                  <input class="quantity" id="stock_item_quantity" data-stock-location-id="{{this.stock_location_id}}" type="number" min="1" value="1">
                </td>
                <td class="actions">
                  <button class="add_variant no-text icon-plus icon_link with-tip" data-stock-location-id="{{this.stock_location_id}}" title="<%= Spree.t(:add) %>" data-action="add"></button>
                </td>
              {{else}}
                <td><%= Spree.t(:out_of_stock) %></td>
                <td>0</td>
              {{/if}}
            </tr>
          {{/each}}
        </tbody>
  </fieldset>
</script>

app/views/spree/admin/variants/_form.html.erb
<div data-hook="admin_variant_form_fields" class="label-block left six columns alpha">
  <div data-hook="variants">
    <% @product.option_types.each do |option_type| %>
      <div class="field" data-hook="presentation">
        <%= label :new_variant, option_type.presentation %>
        <%= f.collection_select 'option_value_ids', option_type.option_values, :id, :presentation,
          { :prompt => true }, { :name => 'variant[option_value_ids][]', :class => 'select2 fullwidth' } %>
      </div>
    <% end %>

    <div class="field" data-hook="sku">
      <%= f.label :sku, Spree.t(:sku) %>
      <%= f.text_field :sku, :class => 'fullwidth' %>
    </div>

    <div class="field" data-hook="price">
      <%= f.label :price, Spree.t(:price) %>
      <%= f.text_field :price, :value => number_to_currency(@variant.price, :unit => ''), :class => 'fullwidth' %>
    </div>

    <div class="field" data-hook="cost_price">
      <%= f.label :cost_price, Spree.t(:cost_price) %>
      <%= f.text_field :cost_price, :value => number_to_currency(@variant.cost_price, :unit => ''), :class => 'fullwidth' %>
    </div>
  </div>
</div>

<div class="right six columns omega label-block" data-hook="admin_variant_form_additional_fields">
  <% [:weight, :height, :width, :depth].each do |field| %>
    <div class="field" data-hook="<%= field %>"><%= f.label field, Spree.t(field) %>
      <% value = number_with_precision(@variant.send(field), :precision => 2) %>
      <%= f.text_field field, :value => value, :class => 'fullwidth' %>
    </div>
  <% end %>
</div>

<div class="clear"></div>

app/views/spree/admin/variants/_split.js.erb
<script type='text/template' id='variant_split_template'>
  <tr class='stock-item-split' data-variant-id='{{variant.id}}'>
    <td colspan='2'>
      Move {{variant.name}} to:
    </td>
    <td colspan='2'>
    <select name="item_stock_location" id='item_stock_location' style='width:100%;'>
      <option></option>
      <optgroup label="Existing Shipments">
        {{#each shipments}}
        <option data-shipment-number='{{this.number}}' value='{{this.stock_location_id}}'>{{this.stock_location.name}}({{this.number}})</option>
        {{/each}}
      </optgroup>
      <optgroup label="New Shipment At Location">
        {{#each variant.stock_items}}
          <option data-new-shipment='true' value='{{this.stock_location_id}}'>{{this.stock_location_name}}</option>
        {{/each}}
      </optgroup>
      </select>
    </td>
    <td>
      <input class="quantity" id="item_quantity" type="number" min="1" value="1" max="{{max_quantity}}">
    </td>
    <td class='actions'>
      <a href='#' class='save-split icon_link icon-ok no-text with-tip' title='Save'></a>
      <a href='#' class='cancel-split icon_link icon-cancel no-text with-tip' title='Cancel'></a>
    </td>
  </tr>
</script>

app/views/spree/admin/variants/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Variants' } %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @variant } %>

<%= form_for [:admin, @product, @variant] do |f| %>
  <fieldset class="no-border-top">
    <div data-hook="admin_variant_edit_form">
      <%= render :partial => 'form', :locals => { :f => f } %>
    </div>

    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/variants/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Variants'} %>

<%# Place for new variant form %>
<div id="new_variant" data-hook></div>

<% if @variants.any? %>
  <table class="index sortable" data-sortable-link="<%= update_positions_admin_product_variants_path(@product) %>">
    <colgroup>
      <col style="width: 5%" />
      <col style="width: 25%" />
      <col style="width: 20%" />
      <col style="width: 20%" />
      <col style="width: 15%" />
      <col style="width: 15%" />
    </colgroup>
    <thead data-hook="variants_header">
      <tr>
        <th colspan="2"><%= Spree.t(:options) %></th>
        <th><%= Spree.t(:price) %></th>
        <th><%= Spree.t(:sku) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @variants.each do |variant| %>
      <tr id="<%= spree_dom_id variant %>" <%= 'style="color:red;"' if variant.deleted? %> data-hook="variants_row" class="<%= cycle('odd', 'even')%>">
        <td class="no-border">
          <span class="handle"></span>
        </td>
        <td><%= variant.options_text %></td>
        <td class="align-center"><%= variant.display_price.to_html %></td>
        <td class="align-center"><%= variant.sku %></td>
        <td class="actions">
          <%= link_to_edit(variant, :no_text => true) unless variant.deleted? %>
          &nbsp;
          <%= link_to_delete(variant, :no_text => true) unless variant.deleted? %>
        </td>
      </tr>
      <% end %>
      <% unless @product.has_variants? %>
        <tr><td colspan="5"><%= Spree.t(:none) %></td></tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/variant')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_product_variant_path(@product) %>!
  </div>
<% end %>

<% if @product.empty_option_values? %>
  <p class='first_add_option_types no-objects-found' data-hook="first_add_option_types">
    <%= Spree.t(:to_add_variants_you_must_first_define) %>
    <%= link_to Spree.t(:option_types), admin_product_url(@product) %>
    <%= Spree.t(:and) %>
    <%= link_to Spree.t(:option_values), admin_option_types_url %>
  </p>
<% else %>
  <% content_for :page_actions do %>
    <ul class="inline-menu" data-hook="toolbar">
      <li id="new_var_link" data-hook>
        <%= link_to_with_icon('icon-plus',
                              Spree.t(:new_variant),
                              new_admin_product_variant_url(@product),
                              :remote => :true,
                              :'data-update' => 'new_variant',
                              :class => 'button'
                             ) %>
      </li>
      <li><%= link_to_with_icon('icon-filter', @deleted.blank? ? Spree.t(:show_deleted) : Spree.t(:show_active), admin_product_variants_url(@product, :deleted => @deleted.blank? ? "on" : "off"), :class => 'button') %></li>
    </ul>
  <% end %>
<% end %>

app/views/spree/admin/variants/new.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @variant } %>

<%= form_for [:admin, @product, @variant] do |f| %>
  <fieldset data-hook="admin_variant_new_form">
    <legend align="center"><%= Spree.t(:new_variant) %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/variants/new.js.erb
$("#new_variant").html('<%= escape_javascript(render :template => 'spree/admin/variants/new', :formats => [:html], :handlers => [:erb]) %>');
$(".select2").select2();
$("#new_var_link").hide();